apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: constructora
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "constructora_web"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  CORS_ALLOWED_ORIGINS: "https://constructora.grupoarquinova.com"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM: "noreply@constructora.com"
  FLYWAY_ENABLED: "true"
  RABBITMQ_AUTO_STARTUP: "true"

