apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: constructora
type: Opaque
stringData:
  DB_USERNAME: "constructora_user"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION_DB_PASSWORD"
  DB_ROOT_PASSWORD: "CHANGE_ME_IN_PRODUCTION_ROOT_PASSWORD"
  REDIS_PASSWORD: "CHANGE_ME_IN_PRODUCTION_REDIS_PASSWORD"
  RABBITMQ_USERNAME: "rabbit_prod_user"
  RABBITMQ_PASSWORD: "CHANGE_ME_IN_PRODUCTION_RABBITMQ_PASSWORD"
  JWT_SECRET: "9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b"
  MAIL_USERNAME: "notificaciones@constructora.com"
  MAIL_PASSWORD: "CHANGE_ME_IN_PRODUCTION_SMTP_PASSWORD"
